### ISSUE TITLE
client_id not being sent during microsoft authentication

### ISSUE THREAD

**Issue by danielneilson** [pdobsan/mailctl#1]
I am trying to set up mailctl with an office365 account. I created an app in the azure console and set `auth_endpoint`, `token_endpoint`, `tenant`, `client_id` and `client_secret` in `services.yaml`. I set the redirect uri to `http://localhost:8080`.

When I visit the redirect uri, authentication fails with the message
`AADSTS900144: The request body must contain the following parameter: 'client_id'.`

**Comment by pdobsan** [comment]
Just to be on the same page make sure you are always using the most recent version, at the moment of writing it is 0.5.3, but can change any time.

> I created an app in the azure console and set `auth_endpoint`, `token_endpoint`, `tenant`, `client_id` and `client_secret` in `services.yaml`.

You need to set only `client_id` and `client_secret`. Did you changed the others too?
The best would be to show your configs here, doctoring the sensitive details.

> I set the redirect uri to `http://localhost:8080`.

Try both this and the original in the template and see what happens. Microsoft's API has some nuances I am not so sure about. I don't have MS accounts, can't really test.

**Comment by danielneilson** [comment]
Thanks for keeping up with this. I'm using the AUR package and am up to date at 0.5.3.

Here is my current `$HOME/.config/services.yaml`. I have tried various permutations of the endpoints, to no effect. I think that `redirect_uri` is wrong.

```
microsoft:
  #auth_endpoint: https://login.microsoftonline.com/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/oauth2/v2.0/authorize
  #token_endpoint: https://login.microsoftonline.com/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/oauth2/v2.0/token
  #redirect_uri: http://localhost:8080
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
  redirect_uri: https://login.microsoftonline.com/common/oauth2/nativeclient
  auth_scope: |
    https://outlook.office365.com/IMAP.AccessAsUser.All
    https://outlook.office365.com/SMTP.Send
    offline_access
  #tenant: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  tenant: common
  client_id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  client_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

I start mailctl with 
```
mailctl authorize microsoft danielneilson@X.com
```

It instructs me to go to `$redirect_uri/start`. If I open
```
https://login.microsoftonline.com/common/oauth2/nativeclient/start
```
I get a 404.

Unfortunately I don't know a lot about oauth2 or microsoft's implementation. I just need to use office365 mail (for work, no choice) over IMAP with `fdm` so that I can get on with my life. When I have a minute I will try to look into microsoft's documentation and will make a note here if I find anything.

Meantime, thank you for your work on mailctl, which looks like it will be a great solution to the problem.

**Comment by pdobsan** [comment]
On Thu, Jun 30, 2022 at 11:28:13AM -0700, Daniel H. Neilson wrote:
> Here is my current `$HOME/.config/services.yaml`. I have tried various
> permutations of the endpoints, to no effect. I think that `redirect_uri`
> is wrong.

You are right, the `redirect_uri` should be `http://localhost:8080` and the
variation when using tenant and substituting it into _endpoints is the most
likely correct.

I am not sure what `client_secret` is or needed here at all. I have also
registered at azure and there was no secret unless you created one but then
it came as a pair of `value` and `secret ID`.

Anyway, now I understand what the error message of `AADSTS900144: The
request body must contain ...` means. Simply MS requires to send http
request's parameters in the request body not in query strings in the URL.
Unfortunately it is not the way the program communicates with google. That
can be changed I think but needs a fundamental rewrite of some parts. Now
that the program is out I have to be careful not to ruin where it works with
google. I'll give it a try, but that would take some time.

**Comment by pdobsan** [comment]
I now think that `tenant: common` is the right setting to use.

I tried to address the `AADSTS900144` error with release 0.6 as far as my interpretation of it goes. Let me know if that has changed anything for you.

**Comment by danielneilson** [comment]
I was able to make some progress.

From Microsoft's oauth2 API docs, it looks like a `query-string` request should be possible. I assembled a url like this (newlines added for readability):

```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize
?client_id=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
&response_type=code
&redirect_uri=http%3A%2F%2Flocalhost%3A8080
&response_mode=query
&scope=https%3A%2F%2Foutlook.office365.com%2FIMAP.AccessAsUser.All
%20https%3A%2F%2Foutlook.office365.com%2FSMTP.Send
%20offline_access
&state=12345
```
When I visit that url using my browser, it starts a proper oauth2 authentication process.

When my `services.yaml` looks like this:
```
microsoft:
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  auth_postmode: query-string
  token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
  token_postmode: request-body
  redirect_uri: http://localhost:8080
  auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
  tenant: common
  client_id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  client_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
and I start `mailctl authorize microsoft danielneilson@X.com` and visit `http://localhost:8080/start`, I would expect to see the same thing as I see when I visit the url above. But instead I get `AADSTS900144` as before. Same if I use `request-body`.

Microsoft will accept query-string requests, so it seems that `mailctl` is not creating a valid request when it starts the `localWebServer`.
