### ISSUE TITLE
localWebServer: request not found

### ISSUE THREAD

**Issue by ArthurBorsboom** [pdobsan/mailctl#12]
I am trying to setup a Microsoft 365 mail account remotely by SSH on a Linux server.

Whichever configuration I try, mailctl keeps ending up in a browser window stating "request not found".

Roughly these are the steps I am doing. 

Allow incoming traffic through the firewall (iptables): TCP/8080
Edit /etc/hosts file making sure localhost refers to the public IP, so the webserver of mailctl attaches to the public IP.
Start mailctl in a SSH window.

Start desktop browser and enter the URL: http://monitor.xxxxxxxx.com:8080/start
A Microsoft password form shows in the browser.

![2022-10-10-154520_1018x737_scrot](https://user-images.githubusercontent.com/6639859/194882962-8aaf4461-3b2f-441f-8dcb-d7aef06fb7f0.png)

I enter the password followed by [Sign in].

The browser gets redirected to:
http://monitor.xxxxxxxx.com:8080/common/login

and the following response appears in the browser window.

![2022-10-10-154619_1018x737_scrot](https://user-images.githubusercontent.com/6639859/194882999-4579ae06-96a1-4678-bdd1-70fdd2befec8.png)

```
localWebServer: request not found ... Request {requestMethod = "POST", httpVersion = HTTP/1.1, rawPathInfo = "/common/login", rawQueryString = "", requestHeaders = [("Host","monitor.xxxxxxxx.com:8080"),("User-Agent","Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"),("Accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"),("Accept-Language","en-US,en;q=0.5"),("Accept-Encoding","gzip, deflate"),("Referer","http://monitor.xxxxxxxx.com:8080/"),("Content-Type","application/x-www-form-urlencoded"),("Content-Length","1330"),("Origin","http://monitor.xxxxxxxx.com:8080"),("DNT","1"),("Connection","keep-alive"),("Upgrade-Insecure-Requests","1")], isSecure = False, remoteHost = 86.70.118.233:47858, pathInfo = ["common","login"], queryString = [], requestBody = , vault = , requestBodyLength = KnownLength 1330, requestHeaderHost = Just "monitor.xxxxxxxx.com:8080", requestHeaderRange = Nothing}
```

services.yaml

```
microsoft:
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  # auth_endpoint: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/authorize
  auth_http_method: GET
  auth_params_mode: query-string
  token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
  # token_endpoint: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token
  token_http_method: POST
  token_params_mode: request-body-form
  redirect_uri: http://localhost:8080
  # redirect_uri: http://monitor.xxxxxxxx.com
  # redirect_uri: http://localhost:8080/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/login
  auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
  # auth_scope: offline_access https://outlook.office.com/Mail.ReadWrite
  client_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

I have tried several configuration options, but the result stays the same.

Do you have any suggestions how to approach this issue?
