### ISSUE TITLE
"thread blocked indefinitely in an MVar operation"  While trying to authorize microsoft account

### ISSUE THREAD

**Issue by alandmoore** [pdobsan/mailctl#28]
I've been using mailctl successfully for about a month now with Microsoft outlook.  Today it stopped working.  Looking at my auth file, it seems the authorization had expired, so I attempted to re-authorize.

In attempting to re-authorize the account, I get the following output:

```
$ mailctl authorize microsoft myemail@mydomain.dom --debug
To grant OAuth2 access to myemail@mydomain.dom visit the local URL below with your browser.
http://localhost:8080/start
sending all parameters in the query string
Request
    {
      host                 = "login.microsoftonline.com"
      port                 = 443
      secure               = True
      requestHeaders       = []
      path                 = "/common/oauth2/v2.0/authorize"
      queryString          = "?client_id=REDACTED&redirect_uri=http%3A%2F%2Flocalhost%3A8080&response_type=code&scope=https%3A%2F%2Foutlook.office365.com%2FIMAP.AccessAsUser.All%20https%3A%2F%2Foutlook.office365.com%2FSMTP.Send%20offline_access&login_hint=myemail%40mydomain.dom"                           
      method               = "GET"
      proxy                = Nothing
      rawBody              = False
      redirectCount        = 10
      responseTimeout      = ResponseTimeoutDefault
      requestVersion       = HTTP/1.1
      proxySecureMode      = ProxySecureWithConnect
     }

Authorization started ... 
mailctl: localWebServer:
ConnectionTimeout
CallStack (from HasCallStack):
  error, called at lib/MailCtl/Authorization.hs:333:22 in mailctl-0.9.2-inplace:MailCtl.Authorization
mailctl: thread blocked indefinitely in an MVar operation

```

The localhost page never comes up.   It takes several seconds for the ConnectionTImeout error to pop up, of course.

**Comment by alandmoore** [comment]
Just attempted re-auth on the currently working computer and it worked flawlessly.  Both computers are running current Arch Linux with identical mailctl configurations.

**Comment by pdobsan** [comment]
Since you have not provided your config files, the dumped .auth file and the relevant syslog entries I am just guessing here.

> I've been using mailctl successfully for about a month now with Microsoft outlook. Today it stopped working. Looking at my auth file, it seems the authorization had expired, so I attempted to re-authorize.

Under normal circumstance the "authorization" (i.e. the `refresh_token` in the .auth file) never expires. The expiration date refers to the `access_token`. So there is no need to (re)authorize again. The renewal of the `access_token` happens automatically. Although you can also trigger it manually by `mailctl renew <email>` that is rather just for testing purposes.

It seems you are using gpg encrypted .auth files so relying on a running `gpg-agent` with an _open_ key. Depending on your setup and runtime conditions the agent expires the keys it keeps from time to time. When that happens `mailctl` "stops working".  The fix is to make sure that the agent provides the _open_ key needed. Once that is done you can check the result with a manual renewal as above.

It is also possible that the `gpg-agent` just died for whatever reason.

**Comment by alandmoore** [comment]
>Since you have not provided your config files, the dumped .auth file and the relevant syslog entries I am just guessing here.

Apologies.  I did not see a list of files or command outputs I should have provided when submitting a bug.

There are no syslog entries logged on my system related to mailctl.

The config.yaml file contains (sans the comments):

services_file: ~/.config/mailctl/services.yaml


```
oauth2_dir: ~/.local/var/mailctl
encrypt_cmd:
  exec: gpg
  args:
    - --encrypt
    - --recipient
    - alan.moore
    - -o
decrypt_cmd:
  exec: gpg
  args:
    - --decrypt
```

The services.yaml file contains:

```
microsoft:
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  auth_http_method: GET
  auth_params_mode: query-string
  token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
  token_http_method: POST
  token_params_mode: request-body-form
  redirect_uri: http://localhost:8080
  auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
  client_id: 08162f7c-0fd2-4200-a84a-f25a4db0b584
  client_secret: TxRBilcHdC6WGBee]fs?QR:SJ8nI[g82
```

If I run `gpg-agent` it reports that it is running and available.  

If I go to the `.local/var/mailctl` directory and run `gpg --decrypt` on the .auth file, it dumps this (without redactions, of course):

```
gpg: encrypted with 3072-bit RSA key, ID 63B40A6933479AB0, created 2023-09-18
      "Alan Moore <myemail@mydomain.dom>"
{"access_token":"REDACTED","email":{"unEmailAddress":"myemail@mydomain.dom"},"exp_date":"2023-11-05 22:19 UTC","expires_in":3877,"refresh_token":"REDACTED","scope":"https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send","service":"microsoft","token_type":"Bearer"}
```

It seems that any command I run, whether `renew`, `refresh`, `access`, etc fails with a connection timeout.  I am connected to the Internet, not behind a filter or proxy of any kind, and able to reach microsoft login via a browser without issue.

Happy to provide any other information if necessary.
