### ISSUE TITLE
common/login 404 with microsoft

### ISSUE THREAD

**Issue by ferdinandyb** [pdobsan/mailctl#5]
First off, thanks for the software, I managed to use it to log in to both my personal and work google mail. Unfortunately I have a third one at microsoft. I'm trying to access it using this config:

```
microsoft:
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  auth_http_method: GET
  auth_params_mode: query-string
  token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
  token_http_method: GET
  token_params_mode: query-string
  redirect_uri: http://localhost:8080
  auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
  client_id: X
  client_secret: Y
```

I set the clien ID from the Azure overview pane, from the line saying: Application (client) ID. I also created a secret under certificates and secrets, and tried with using both the `value` and the `secret id` just in case. Both cases lead to getting a login screen with the proper background for my organisation on `localhost:8080/start`, but after entering my password I get redirected to `localhost:8080/common/login` where I get a 404 and the following displayed on screen:

```
localWebServer: request not found ... Request {requestMethod = "POST", httpVersion = HTTP/1.1, rawPathInfo = "/common/login", rawQueryString = "", requestHeaders = [("Host","localhost:8080"),("Connection","keep-alive"),("Content-Length","1634"),("Cache-Control","max-age=0"),("sec-ch-ua","\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\""),("sec-ch-ua-mobile","?0"),("sec-ch-ua-platform","\"Linux\""),("Origin","http://localhost:8080"),("Upgrade-Insecure-Requests","1"),("DNT","1"),("Content-Type","application/x-www-form-urlencoded"),("User-Agent","Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36"),("Accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"),("Sec-Fetch-Site","same-origin"),("Sec-Fetch-Mode","navigate"),("Sec-Fetch-User","?1"),("Sec-Fetch-Dest","document"),("Referer","http://localhost:8080/"),("Accept-Encoding","gzip, deflate, br"),("Accept-Language","hu-HU,hu;q=0.9"),("Cookie","CkTst=G1659816542347; brcap=0; clrc={%2219211%22%3a[%22yXuYioga%22%2c%22nXGRaMn2%22]}; wlidperf=FR=L&ST=1659816558812")], isSecure = False, remoteHost = 127.0.0.1:46164, pathInfo = ["common","login"], queryString = [], requestBody = , vault = , requestBodyLength = KnownLength 1634, requestHeaderHost = Just "localhost:8080", requestHeaderRange = Nothing}
```

Versions `0.6.2` and `0.6.4` produce the same results. Am I doing something wrong here?
