### ISSUE TITLE
authorize fails with "does not exist"

### ISSUE THREAD

**Issue by titaniumbones** [pdobsan/mailctl#6]
Hello,

I'm trying to get myself oriented with this new tool. So far I don't seem to be able to run the program at all. I have created `config.yaml` and `services.yaml` in `~/.config/mailctl/`, with the ofllowing ocntent

```yaml
# The primary purpose of mailctl is providing IMAP/SMTP clients with the
# capabilities of renewal and authorization of OAuth2 credentials. 
# Accordingly only the OAuth2 related config entries are mandatory.

# These four entries should be use for OAuth2 access method
services_file: /home/matt/.config/mailctl/services.yaml
oauth2_dir: /home/matt/.local/var/mailctl
# This encryption method using gnupg.
# Alternatives like gnome-keyring can also be configured here.
encrypt_cmd:
  exec: gpg
  args:
    - --encrypt
    - --recipient
    - [my key]
    - -o
decrypt_cmd:
  exec: gpg
  args:
    - --decrypt

# Only if you are using fdm
# fdm_config: /YOUR-HOME-DIRECTORY/.config/fdm/fdm.conf
# fdm_accounts: /YOUR-HOME-DIRECTORY/.config/fdm/accounts.conf

# Only if you are running mailctl directly by cron
cron_indicator: /home/matt/.local/var/mailctl/fdm-cron-enabled

# Only if you are using a password manager for traditional access methods
# This is an example of using `pass`
# password_store: /YOUR-HOME-DIRECTORY/.local/var/password-store
# pass_cmd:
#   exec: pass
#   args:
#     - email/
```
and 
```yaml
microsoft:
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  auth_http_method: GET
  auth_params_mode: query-string
  token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
  token_http_method: GET
  token_params_mode: query-string
  redirect_uri: http://localhost:8080
  auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
  client_id: 08162f7c-0fd2-4200-a84a-f25a4db0b584
  client_secret: TxRBilcHdC6WGBee]fs?QR:SJ8nI[g82
```
client id and secret are taken from Thunderbird's values. 

When I try to run `mailctl authorize microsoft matt.price@utoronto.ca`, I get:
```
 mailctl --debug authorize microsoft matt.price@utoronto.ca 
mailctl: crontab: readCreateProcessWithExitCode: posix_spawnp: does not exist (No such file or directory)
```

any hints as to what might be going on?

Again, thank you!
matt
